# Generated by Django 4.1.4 on 2022-12-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='description',
            field=models.TextField(default='No Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='name',
            field=models.CharField(default='Name', max_length=255),
            preserve_default=False,
        ),
    ]
