# Generated by Django 4.1.4 on 2022-12-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tickets_description_tickets_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
