# Generated by Django 4.1.4 on 2022-12-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tickets_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='is_updated_by_admin',
            field=models.CharField(default=None, max_length=55),
        ),
    ]
