# Generated by Django 4.1.4 on 2022-12-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tickets_is_updated_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickets',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
